### ISSUE TITLE
Server Pod fail to start : Error while setting up the handler. [Solved]

### ISSUE THREAD

**Issue by mahzoun** [Mirantis/k8s-netchecker-server#118]
I used `deployment.yaml` to start the netchecker server, I got the following error in pods logs:
```
I1108 09:58:45.742276       1 server.go:46] K8s netchecker. Compiled at: 20170822-12:27:01-UTC
I1108 09:58:45.742349       1 server.go:51] Start listening on 0.0.0.0:8081
E1108 09:58:46.943818       1 storer_k8s.go:62] the server could not find the requested resource
E1108 09:58:46.943848       1 server.go:55] Error while setting up the handler. Details: the server could not find the requested resource
panic: the server could not find the requested resource

goroutine 1 [running]:
panic(0x11d6120, 0xc420534c60)
	/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x1a1
main.main()
	/home/travis/gopath/src/github.com/Mirantis/k8s-netchecker-server/cmd/server.go:56 +0x658

```
All agents are running and sending logs to server but since it's down they got `getsockopt: no route to host`

**Comment by AlexeyKasatkin** [comment]
Hi mahzoun. What is your k8s version? deployment.yml example uses k8s TPR which is deprecated and is not supported in k8s v.1.8. To get netchecker workable with k8s v.1.8 and later, you will need to configure netchecker server to use etcd, as in "deployment_etcd.yml" example.

**Comment by mahzoun** [comment]
The version is 1.8.1, thanks I think you are right.
