### ISSUE TITLE
Make possible to test custom payload size

### ISSUE THREAD

**Issue by adidenko** [Mirantis/k8s-netchecker-server#28]
By default agent sends small amount of data which is lower than default MTU size (1500). So if cluster has problems with MTU configuration, netchecker will not detect those since it will not trigger packet fragmentation.

We can implement a separate parameter which would simply add some payload to agent JSON report which should be then discarded on the server side. This will allow netchecker to simply test network MTU and packet fragmentation.

It should be possible to configure this parameter during the runtime and see the current size of additional payload in agents' report.

**Comment by aateem** [comment]
Resolved by this pull request https://github.com/Mirantis/k8s-netchecker-agent/pull/6 into the agent project.
