### ISSUE TITLE
Add ability to track last connectivity issue (or even issues history) for every particular agent.

### ISSUE THREAD

**Issue by AlexeyKasatkin** [Mirantis/k8s-netchecker-server#36]
Now netchecker server remembers (and returns) only current connectivity status with its every known agent. So, flapping issues (or even long connectivity issue after the connection is restored) can be missed.
Need to add an ability to track connectivity status changes so that user can see there was a connectivity issue(s) in the past.

**Comment by adidenko** [comment]
Let's make a metrics endpoint to report such advanced info/stats. Those metrics should be in Prometheus friendly format. With such feature cloud operators will be able to pull metrics and configure alerts in their monitoring system (set severity based on errors rate, etc).
