### ISSUE TITLE
Fix gofmt issue (goreportcard)

### ISSUE THREAD

**Issue by aarzhanov** [Mirantis/k8s-netchecker-server#62]
https://goreportcard.com/report/github.com/Mirantis/k8s-netchecker-server#gofmt

gofmt 83%

Gofmt formats Go programs. We run gofmt -s on your code, where -s is for the "simplify" command
k8s-netchecker-server/pkg/utils/handler.go
Line 1: warning: file is not gofmted with -s (gofmt)

**Comment by aarzhanov** [comment]
Don't forget push button "Refresh now" in goreportcard.

**Comment by AlexeyKasatkin** [comment]
Fixed in https://github.com/Mirantis/k8s-netchecker-server/pull/83
