### ISSUE TITLE
Latency metrics and monitoring

### ISSUE THREAD

**Issue by adidenko** [Mirantis/k8s-netchecker-server#90]
We should introduce new metrics to monitor latency between agents, server and preferably some external hosts:

- **ncagent_server_latency** - gauge type. Network delay (in ms) between agent and server. Labels: `agent` - agent name, similar to existing counters
- **ncagent_host_latency** - gauge type. Network delay between agent and external host. Labels: `agent` - agent name, similar to existing counters, `host` - host/IP we're checking latency for. List of external hosts for this check should be passed to netchecker agents via ENV variables or CLI arguments.

**Comment by AlexeyKasatkin** [comment]
Fixed by https://github.com/Mirantis/k8s-netchecker-server/pull/96
